# yaml-language-server: $schema=./_schema.json

name: Publish

on:
  workflow_call:
    inputs:
      dist:
        description: The directory from which the package will be publish
        default: ./
        required: false
        type: string
      dry:
        description: Perform a dry run of the release
        default: false
        required: false
        type: boolean
      node:
        description: The version of Node.js used
        default: '20'
        required: false
        type: string
      skip:
        description: Skip jobs
        default: false
        required: false
        type: boolean
      debug:
        description: Debug jobs
        default: false
        required: false
        type: boolean

env:
  # General Options
  name: semantic-release-config
  version: ${{ github.ref_name }}
  node: '20'
  debug: false
  # Timeouts (in minutes)
  timeout-setup: 10
  timeout-tests: 30
  timeout-release: 10
  # Environment Variables
  CI_DEBUG: ${{ vars.CI_DEBUG }}
  CI_TIMEOUT_RELEASE: ${{ vars.CI_TIMEOUT_RELEASE }}
  CI_TIMEOUT_SETUP: ${{ vars.CI_TIMEOUT_SETUP }}
  CI_TYPE: ${{ vars.CI_TYPE }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NODE_ENV: production
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Publish
    if: github.repository.archived != true
    runs-on: ubuntu-20.04
    container:
      image: node:20
    steps:
      - name: Init
        id: init
        run: |
          echo "__SKIP=${{ inputs.skip }}" >> $GITHUB_ENV
          echo "__DEBUG=${{ inputs.debug }}" >> $GITHUB_ENV
          echo "__TIMEOUT_SETUP=${{ env.CI_TIMEOUT_SETUP || fromJSON(env.timeout-setup) }}" >> $GITHUB_ENV
          echo "__TIMEOUT_RELEASE=${{ env.CI_TIMEOUT_RELEASE || fromJSON(env.timeout-release) }}" >> $GITHUB_ENV

      - name: Debug
        id: debug
        if: >-
          fromJSON(inputs.debug) == true &&
          fromJSON(env.__SKIP) != true
        run: |
          echo "RUNNER_DEBUG=${{ fromJSON(env.__DEBUG) }}" >> $GITHUB_ENV
          echo "DEBUG=${{ fromJSON(env.__DEBUG) }}" >> $GITHUB_ENV

      - name: Setup
        id: setup
        uses: actions/download-artifact@v3
        timeout-minutes: ${{ fromJSON(env.__TIMEOUT_SETUP) }}
        if: fromJSON(env.__SKIP) != true
        with:
          name: build-artifacts
          path: ${{ inputs.dist }}

      - name: Publish
        id: publish
        timeout-minutes: ${{ fromJSON(env.__TIMEOUT_PUBLISH) }}
        if: fromJSON(env.__SKIP) != true
        run: npx semantic-release
