# yaml-language-server: $schema=./_schema.json

name: Release

on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  build:
    name: BUILD
    if: github.repository.archived != true
    uses: .github/workflows/build.yml
    with:
      node: '20'

  publish:
    name: PUBLISH
    needs: [build]
    if: github.repository.archived != true
    uses: .github/workflows/publish.yml
    with:
      dist: 'dist'
